# Dockerfile
FROM ollama/ollama

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy the entrypoint script into the container
COPY entrypoint-ollama.sh /app/entrypoint-ollama.sh

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint-ollama.sh

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint-ollama.sh"]