# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install -y postgresql-client
RUN pip install --no-cache-dir -r requirements.txt
RUN crawl4ai-setup

# Copy the current directory contents into the container at /app
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Copy the entrypoint script into the container
COPY entrypoint-agent.sh /app/entrypoint-agent.sh

# Make the entrypoint script executable
RUN chmod +x /app/entrypoint-agent.sh

# Set the entrypoint
ENTRYPOINT ["/app/entrypoint-agent.sh"]
